version: '3.8'
services:
  # Primary node
  mongo-primary:
    image: mongo:latest
    container_name: mongo-primary
    restart: always
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - app

  # Secondary node 1
  mongo-secondary1:
    image: mongo:latest
    container_name: mongo-secondary1
    restart: always
    ports:
      - "27018:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - app

  # Secondary node 2
  mongo-secondary2:
    image: mongo:latest
    container_name: mongo-secondary2
    restart: always
    ports:
      - "27019:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - app

  # Initializer
  mongo-init:
    image: mongo:latest
    container_name: mongo-init
    depends_on:
      - mongo-primary
      - mongo-secondary1
      - mongo-secondary2
    entrypoint: >
      bash -c "
      sleep 30 &&
      mongosh --host mongo-primary:27017 --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [
            { _id: 0, host: \"mongo-primary:27017\", priority: 2 },
            { _id: 1, host: \"mongo-secondary1:27017\", priority: 1 },
            { _id: 2, host: \"mongo-secondary2:27017\", priority: 1 }
          ]
        })'
      "
    networks:
      - app

networks:
  app:
    driver: bridge